### PR TITLE
[WIP] CP validations-Luis

### PR DESCRIPTION
**Pull request by Tav0**
- Simple validations for conference for now.
- Adding the submissions validations to this as well and reuse the component.
- Needs complexed validations.

### CODE REVIEW

**Comment by leodomingo** [comment]
Be careful with this because I added a new validation for the slug on my branch.

**Comment by Tav0** [comment]
@leodomingo check this PR on how I make the validation component reusable for the fields.

**Comment by leodomingo** [comment]
Is it all bad if submission titles are sometimes the same within the same conference?

**Comment by Ghalko** [comment]
@leodomingo As long as we aren't basing our ids off of submission titles then I think it should be fine.

**Comment by leodomingo** [comment]
Replaced this guy with PR #81 , closing now

**Pull request closed without merging**
