### PR TITLE
Login django user after osf authorization

### PR DESCRIPTION
**Pull request by jnayak1**
Logs in user to django after oauth. Session for django app stored in user's browser.

Login workflow:
1. User navigates to localhost:4200/login
2. User is redirected to osf oauth authorization url
3. User logs in or creates osf account
4. User allows osf-meetings permission (callback url set to ember)
5. Callback url sent from ember to django via get request
6. Django receives code for user through callback url
7. Django posts to osf to get token for user
8. Django uses token to get information about user (like their user id)
9. Django creates osf-meetings account for user unless they already have an account
10. Django logs user in putting a session cookie in their browser. 
11. Ember redirects user to home page

Concerns:
- Currently there is no password for the user. The user is being logged in based solely on the response from /users/me to osf api v2. This request is being made from django. I would think this would be secure however I am not sure.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
@jnayak1 Looks like you're playing whack-a-mole with pyc files (197422d0c55381bf31e629b9748e0c2b09670574 92398e8296bbcb4b80a795abacf2c2e781d38458 7f9be12c8cb23bfdc02a2e069ee031c6118a8675). Check out [`.gitignore`](https://help.github.com/articles/ignoring-files/) for a way to avoid accidentally adding `*.pyc` files in the first place. :-)

**Comment by chadwhitacre** [comment]
##### Punchlist
- [x] remove *.pyc files on a separate PR
- [ ] rebase on develop

**Comment by jnayak1** [comment]
Yeah, when we switched repositories, we didn't keep our gitignore so people had pushed .pyc files. I was removing them.

**Comment by chadwhitacre** [comment]
> Yeah, when we switched repositories, we didn't keep our gitignore so people had pushed .pyc files. I was removing them.

Ah, got it, sorry. Let's do that in a separate PR, since it's unrelated to the scope of this PR.

**Comment by chadwhitacre** [comment]
@jnayak1 Do you know how to use `git rebase -i` to remove commits from a branch?

**Comment by chadwhitacre** [comment]
Actually, it looks like you and @Ghalko removed pyc files in cad09f61596df3b639cbe501262d7912af910905, ya?

**Comment by jnayak1** [comment]
> @jnayak1 Do you know how to use git rebase -i to remove commits from a branch?

I have never done it but I can look into that. I was just going to pull the changes from develop and merge.

**Comment by jnayak1** [comment]
> Actually, it looks like you and @Ghalko removed pyc files in cad09f6, ya?

Yes, it looks like @Ghalko removed them. We were working on these PRs concurrently so it looks like we overlapped some.

**Comment by chadwhitacre** [comment]
> I was just going to pull the changes from develop and merge.

Up to you. Rebasing allows you to maintain a clean history for your PR, so that it's easier for yourself and others to read and review. However, it takes more skill to do effectively, compared to merging. Merging is COS's standard practice. :)

**Comment by jnayak1** [comment]
> Up to you. Rebasing allows you to maintain a clean history for your PR, so that it's easier for yourself and others to read and review. However, it takes more skill to do effectively, compared to merging. Merging is COS's standard practice. :)

Ah! Good to know!

**Comment by chadwhitacre** [comment]
Bringing over from [Jira](https://openscience.atlassian.net/browse/OSF-6597?focusedCommentId=35309&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-35309) ...

> Chris Wisecarver said the code and workflow looked fine, however he recommends using https://github.com/pennersr/django-allauth instead. It's a widely used plugin and has been tested extensively. 

Are you planning to switch to `django-allauth` on this PR?

**Comment by jnayak1** [comment]
> Are you planning to switch to django-allauth on this PR?

We have something working right now, so I am a little hesitant to spend the time to switch over at the moment. I feel like time would be better spent rolling out features for an MVP and then come back to that. Either way though.

**Comment by chadwhitacre** [comment]
Okay. Sounds like the next step here is to sync w/ develop one way or another. Other than that I'm going to get out of your way until I'm more up to speed on what this new repo is all about. :-)

**Pull request closed without merging**
